# Generated by Django 4.2.4 on 2023-08-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
